apiVersion: skaffold/v2beta18
kind: Config
build:
  artifacts:
  - image: registry.replicated.com/library/retraced
    context: ./
    docker:
      dockerfile: ./Dockerfile.skaffold

deploy:
  kustomize:
    paths:
    - ./kustomize/overlays/skaffold
