apiVersion: apps/v1
kind: Deployment
metadata:
  name: retraced-api
spec:
  template:
    spec:
      initContainers:
        - name: bootstrap
          image: registry.replicated.com/library/retraced
      containers:
        - name: api
          image: registry.replicated.com/library/retraced
          env:
            - name: PG_SEARCH
              value: ""
            - name: LOG_LEVEL
              value: debug
