apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron
  namespace: 'divolgin'
spec:
  template:
    spec:
      containers:
        - name: cron
          image: registry.replicated.com/shipretraced/retraced

