apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: 'divolgin'
spec:
  template:
    spec:
      containers:
        - name: processor
          image: registry.replicated.com/shipretraced/retraced
