apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      imagePullSecrets:
        - $patch: delete
      affinity:
        $patch: delete
      initContainers:
        - name: bootstrap
          image: registry.replicated.com/shipretraced/retraced
      containers:
        - name: api
          image: registry.replicated.com/shipretraced/retraced

